#!/usr/bin/env bash
#
# claude-upgrade-advisor -- environment snapshot
#
# Prints a markdown report of the Claude Code configuration that is actually in
# effect: the global settings, the installed extensions, and the current
# project's harness files.
#
# Everything printed here lands in a conversation, so secrets are masked on the
# way out. Masking is deliberately aggressive: it is better to redact a
# harmless value than to leak a live token.
#
# Usage: snapshot-env.sh [project_dir]     (defaults to $PWD)

set -u

project_dir="${1:-$PWD}"
config_dir="${CLAUDE_CONFIG_DIR:-$HOME/.claude}"

# Files bigger than this are summarised rather than printed in full, to keep
# the snapshot from swamping the context window.
MAX_INLINE_BYTES=8000

# ------------------------------------------------------------------- masking

# Case-insensitive credential-ish words. Spelled out as character classes
# because BSD sed (macOS) has no inline case-insensitive flag.
_CRED_WORDS='[Tt][Oo][Kk][Ee][Nn]|[Kk][Ee][Yy]|[Ss][Ee][Cc][Rr][Ee][Tt]|[Pp][Aa][Ss][Ss][Ww][Oo][Rr][Dd]|[Pp][Aa][Ss][Ss][Ww][Dd]|[Cc][Rr][Ee][Dd][Ee][Nn][Tt][Ii][Aa][Ll]|[Aa][Uu][Tt][Hh]|[Pp][Aa][Ss][Ss][Pp][Hh][Rr][Aa][Ss][Ee]'

mask() {
  # Redact anything that looks like a credential. Deliberately over-redacts:
  # a field merely *named* like a secret loses its value even if harmless.
  sed -E \
    -e 's/("[^"]*('"$_CRED_WORDS"')[^"]*"[[:space:]]*:[[:space:]]*")[^"]*(")/\1<REDACTED>\3/g' \
    -e 's/([A-Za-z_]*('"$_CRED_WORDS"')[A-Za-z_]*[[:space:]]*=[[:space:]]*)[^[:space:]",]+/\1<REDACTED>/g' \
    -e 's/(Bearer|bearer)[[:space:]]+[A-Za-z0-9._~+\/-]+=*/\1 <REDACTED>/g' \
    -e 's/(ghp|gho|ghu|ghs|ghr)_[A-Za-z0-9]+/\1_<REDACTED>/g' \
    -e 's/github_pat_[A-Za-z0-9_]+/github_pat_<REDACTED>/g' \
    -e 's/sk-ant-[A-Za-z0-9_-]+/sk-ant-<REDACTED>/g' \
    -e 's/sk-[A-Za-z0-9_-]{16,}/sk-<REDACTED>/g' \
    -e 's/(xoxb|xoxp|xoxa|xapp)-[A-Za-z0-9-]+/\1-<REDACTED>/g' \
    -e 's/AKIA[0-9A-Z]{12,}/AKIA<REDACTED>/g' \
    -e 's/AIza[A-Za-z0-9_-]{30,}/AIza<REDACTED>/g' \
    -e 's/glpat-[A-Za-z0-9_-]+/glpat-<REDACTED>/g' \
    -e 's/(eyJ[A-Za-z0-9_-]{10,})\.[A-Za-z0-9._-]+/<REDACTED_JWT>/g'
}

file_size() {
  wc -c < "$1" 2>/dev/null | tr -d ' ' || echo 0
}

emit_file() {
  # emit_file <label> <path> <fence-language>
  _label="$1"
  _path="$2"
  _lang="${3:-}"
  if [ ! -f "$_path" ]; then
    printf '### %s\n\nNot present: `%s`\n\n' "$_label" "$_path"
    return 0
  fi
  _size="$(file_size "$_path")"
  printf '### %s\n\n`%s` (%s bytes)\n\n' "$_label" "$_path" "$_size"
  if [ "$_size" -gt "$MAX_INLINE_BYTES" ] 2>/dev/null; then
    printf 'Truncated to the first %s bytes. Read the file directly if the tail matters.\n\n' "$MAX_INLINE_BYTES"
    printf '```%s\n' "$_lang"
    head -c "$MAX_INLINE_BYTES" "$_path" 2>/dev/null | mask
    printf '\n```\n\n'
  else
    printf '```%s\n' "$_lang"
    mask < "$_path" 2>/dev/null
    printf '\n```\n\n'
  fi
}

list_dir() {
  # list_dir <label> <path>
  _label="$1"
  _path="$2"
  printf '### %s\n\n' "$_label"
  if [ ! -d "$_path" ]; then
    printf 'Not present: `%s`\n\n' "$_path"
    return 0
  fi
  printf '`%s`\n\n```\n' "$_path"
  (cd "$_path" 2>/dev/null && find . -maxdepth 2 -not -name '.DS_Store' | sort | head -60) || true
  printf '```\n\n'
}

# --------------------------------------------------------------------- report

printf '# Claude environment snapshot\n\n'
printf 'Generated by claude-upgrade-advisor. Credentials are masked as `<REDACTED>`.\n\n'

printf '## Runtime\n\n'
printf '| Item | Value |\n|---|---|\n'
printf '| Claude Code version | %s |\n' "$(claude --version 2>/dev/null || echo 'unavailable')"
printf '| Platform | %s |\n' "$(uname -sr 2>/dev/null || echo unknown)"
printf '| Config directory | `%s` |\n' "$config_dir"
printf '| CLAUDE_CONFIG_DIR set | %s |\n' "$([ -n "${CLAUDE_CONFIG_DIR:-}" ] && echo yes || echo 'no (default)')"
printf '| Project directory | `%s` |\n' "$project_dir"
printf '| Project is a git repo | %s |\n' "$([ -d "$project_dir/.git" ] && echo yes || echo no)"
printf '| Today | %s |\n' "$(date +%Y-%m-%d 2>/dev/null)"
printf '\n'

printf '## Global configuration\n\n'
emit_file "Global settings.json" "$config_dir/settings.json" json
emit_file "Global settings.local.json" "$config_dir/settings.local.json" json
emit_file "Global CLAUDE.md" "$config_dir/CLAUDE.md" markdown

printf '## Installed extensions\n\n'
emit_file "Installed plugins" "$config_dir/plugins/installed_plugins.json" json
emit_file "Known marketplaces" "$config_dir/plugins/known_marketplaces.json" json
list_dir "User skills" "$config_dir/skills"
list_dir "User agents" "$config_dir/agents"

printf '## Project harness\n\n'
emit_file "Project CLAUDE.md" "$project_dir/CLAUDE.md" markdown
emit_file "Project settings.json" "$project_dir/.claude/settings.json" json
emit_file "Project settings.local.json" "$project_dir/.claude/settings.local.json" json
emit_file "Project MCP servers" "$project_dir/.mcp.json" json
emit_file "Project hooks" "$project_dir/.claude/hooks/hooks.json" json
list_dir "Project agents" "$project_dir/.claude/agents"
list_dir "Project skills" "$project_dir/.claude/skills"
list_dir "Project commands" "$project_dir/.claude/commands"

printf '## Advisor state\n\n'
emit_file "state.json" "$config_dir/claude-upgrade-advisor/state.json" json
if [ -f "$config_dir/claude-upgrade-advisor/seen-models" ]; then
  printf '### Models seen in this environment\n\n```\n'
  sort -u "$config_dir/claude-upgrade-advisor/seen-models" 2>/dev/null
  printf '```\n\n'
fi

printf -- '---\n\nEnd of snapshot.\n'
